Milestone 2 components
KerronKing/react-calculator pull request #2
Opened 2020-02-12 19:52 UTC by KerronKing

In this milestone I:

- Created an App component to render the Display and ButtonPanel components.
- Created a Display component that accepts the incoming result as a string.
- Created a Button component that accepts a name prop as a string.
- Created a ButtonPanel component that renders the buttons in a calculator panel format.

2020-02-12 21:00 UTC, shloch requested changes
## hello @KerronKing 

Nice work, nothing to report, apart of file organisation as prescribed by project description 😊😊

Please just correct this and get a thumbs up.. (waiting for last re-review)

Happy coding

2020-02-12 21:00 UTC, shloch commented on src/app.js
> +ReactDOM.render(<App />, document.getElementById('root'));
- this App component should be in folder `src/components`

2020-02-12 21:00 UTC, shloch commented on src/display.js
> +export default Display;
- this component should be in folder `src/components`

2020-02-12 21:00 UTC, shloch commented on src/button.js
> +export default Button;
- this component should be in folder `src/components`

2020-02-12 21:00 UTC, shloch commented on src/button-panel.js
> +  <div>
- this component should be in folder `src/components`

2020-02-12 22:06 UTC, KerronKing commented
All files moved to components folder as per instructions.

2020-02-13 00:20 UTC, Oghenebrume50 approved these changes
### STATUS: APPROVED

Hi @KerronKing this looks great now, thanks for making changes, please merge and move on to the next milestone :+1:   **This is approved** :slightly_smiling_face: 

**RAPHAEL NORIODE** :sunglasses:

2020-02-13 01:12 UTC, merged